  "use strict";
  /*
    Single-file integration of the supplied finance dashboard and Financial Tycoon
    module. The original TypeScript game model is represented below as validated
    plain JavaScript so it runs without a bundler. This is a browser-only demo;
    it deliberately does not claim to process payments, hold passwords, or move money.
  */
  const STORAGE_KEY = "goalgrow.unified.v1";
  const MAX_RUPEES = 1000000000;
  const MAX_POINTS = 1000000000;
  const MAX_EMPIRE_LEVEL = 100;
  const FREE_ACTIVE_GOAL_LIMIT = 3;
  const PREMIUM_MONTHLY_PRICE = 299;
  const TRIAL_DAYS = 7;
  const COINS_PER_RUPEE = 100;
  const MIN_CASHOUT_COINS = 1000;
  const BUILDINGS = Object.freeze([
    {id:"starter",name:"Starter House",icon:"🏠",unlock:1,description:"Your first financial foothold.",costs:[100,160,240,360,520]},
    {id:"bank",name:"Savings Bank",icon:"🏦",unlock:2,description:"A stable base for better habits.",costs:[300,450,650,900,1250]},
    {id:"tower",name:"Investment Tower",icon:"📊",unlock:3,description:"A landmark for consistent investing.",costs:[750,1050,1450,1950,2600]},
    {id:"business",name:"Business Center",icon:"🏢",unlock:4,description:"A hub for your growing plan.",costs:[1500,2100,2850,3750,4900]},
    {id:"district",name:"Financial District",icon:"🏙️",unlock:5,description:"A city district built on progress.",costs:[3000,4050,5350,6900,8750]},
    {id:"empire",name:"Empire Headquarters",icon:"🌆",unlock:6,description:"The final property in your city.",costs:[6000,7900,10100,12700,15700]}
  ]);
  const CHALLENGES = Object.freeze([
    {id:"track",label:"Track today’s spending",points:20,xp:30},
    {id:"review",label:"Review a weekly budget",points:45,xp:55},
    {id:"learn",label:"Learn one finance concept",points:30,xp:40}
  ]);
  const DEFAULT_STATE = Object.freeze({
    schema:1, points:1250, gameCoins:0, goals:[
      {id:"home",name:"Dream Home",description:"Build a down-payment fund",target:500000,invested:200000,mode:"Monthly SIP",monthly:10000,completed:false},
      {id:"car",name:"New Car",description:"Plan the next car without rushing",target:300000,invested:120000,mode:"Monthly SIP",monthly:8000,completed:false},
      {id:"study",name:"Higher Studies",description:"Fund education with confidence",target:800000,invested:300000,mode:"Lump sum",monthly:0,completed:false}
    ], transactions:[], exchangeRequests:[],
    tycoon:{level:1,xp:0,buildings:{},challenges:{},gamesPlayed:0,lastGameResult:"No round played yet."},
    subscription:{status:"free",trialStartedAt:null,trialEndsAt:null,billingConsentAt:null,cancelledAt:null,lastWeeklyBonusWeek:""},
    profile:{username:"Rick",photo:"",verifiedContact:"",linkedAccounts:[{id:"acct-1",name:"GoalGrow Bank",last4:"4821"}],pendingChange:null}
  });
  const memoryStorage = new Map();
  const storage = typeof localStorage !== "undefined" ? localStorage : {getItem:k=>memoryStorage.get(k)||null,setItem:(k,v)=>memoryStorage.set(k,v)};
  const clone = value => JSON.parse(JSON.stringify(value));
  const now = () => Date.now();
  const asInt = (value, fallback=0, min=0, max=MAX_POINTS) => {
    const number = Number(value);
    return Number.isSafeInteger(number) && number >= min && number <= max ? number : fallback;
  };
  const clamp = (value,min,max) => Math.min(max,Math.max(min,value));
  const asText = (value,fallback,max=120) => typeof value === "string" ? value.trim().slice(0,max) || fallback : fallback;
  const makeId = prefix => prefix + "-" + (globalThis.crypto?.randomUUID?.() || (now().toString(36)+Math.random().toString(36).slice(2,9)));
  const money = amount => "₹" + asInt(amount,0,0,MAX_RUPEES).toLocaleString("en-IN");
  const dateTime = timestamp => new Date(timestamp).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"});
  const xpForLevel = level => 500 + (asInt(level,1,1,MAX_EMPIRE_LEVEL)-1)*250;
  const weekKey = timestamp => { const d=new Date(timestamp); const monday=new Date(d); monday.setHours(0,0,0,0); monday.setDate(d.getDate()-((d.getDay()+6)%7)); return monday.toISOString().slice(0,10); };
  const safePhotoUrl = value => { try { const u=new URL(value); return u.protocol === "https:" ? u.href : ""; } catch { return ""; } };

  function normaliseState(raw){
    const seed=clone(DEFAULT_STATE), source=raw&&typeof raw==="object"?raw:{};
    const result={...seed}; result.points=asInt(source.points,seed.points); result.gameCoins=asInt(source.gameCoins,0);
    const seen=new Set();
    result.goals=(Array.isArray(source.goals)?source.goals:seed.goals).slice(0,200).map((goal,index)=>{
      const target=asInt(goal?.target,100,100,MAX_RUPEES); const invested=clamp(asInt(goal?.invested,0,0,MAX_RUPEES),0,target);
      let id=asText(goal?.id,"goal-"+index,80); while(seen.has(id)) id+="-"+index; seen.add(id);
      const completed=invested===target;
      return {id,name:asText(goal?.name,"Untitled goal",60),description:asText(goal?.description,"Financial goal",120),target,invested,mode:goal?.mode==="Lump sum"?"Lump sum":"Monthly SIP",monthly:clamp(asInt(goal?.monthly,0,0,MAX_RUPEES),0,target),completed,completedAt:completed?asInt(goal?.completedAt,0,0,Number.MAX_SAFE_INTEGER):null,completionAwarded:completed?Boolean(goal?.completionAwarded):false};
    });
    result.transactions=(Array.isArray(source.transactions)?source.transactions:[]).slice(0,100).map((t,index)=>({id:asText(t?.id,"tx-"+index,100),label:asText(t?.label,"Account activity",80),kind:asText(t?.kind,"Activity",40),amount:asInt(t?.amount,0,-MAX_POINTS,MAX_POINTS),createdAt:asInt(t?.createdAt,now(),0,Number.MAX_SAFE_INTEGER)}));
    result.exchangeRequests=(Array.isArray(source.exchangeRequests)?source.exchangeRequests:[]).slice(0,100).map((r,index)=>({id:asText(r?.id,"exchange-"+index,100),coins:asInt(r?.coins,0),rupees:asInt(r?.rupees,0,0,MAX_RUPEES),accountId:asText(r?.accountId,"",100),status:"Pending demo",createdAt:asInt(r?.createdAt,now(),0,Number.MAX_SAFE_INTEGER)}));
    const rawTycoon=source.tycoon&&typeof source.tycoon==="object"?source.tycoon:{};
    result.tycoon={level:asInt(rawTycoon.level,1,1,MAX_EMPIRE_LEVEL),xp:asInt(rawTycoon.xp,0,0,MAX_POINTS),buildings:{},challenges:{},gamesPlayed:asInt(rawTycoon.gamesPlayed,0),lastGameResult:asText(rawTycoon.lastGameResult,"No round played yet.",120)};
    BUILDINGS.forEach(def=>{result.tycoon.buildings[def.id]=asInt(rawTycoon.buildings?.[def.id],0,0,5);});
    CHALLENGES.forEach(def=>{const claimed=asText(rawTycoon.challenges?.[def.id],"",20); result.tycoon.challenges[def.id]=/^\d{4}-\d{2}-\d{2}$/.test(claimed)?claimed:"";});
    let safety=0; while(result.tycoon.level<MAX_EMPIRE_LEVEL && result.tycoon.xp>=xpForLevel(result.tycoon.level) && safety++<MAX_EMPIRE_LEVEL){result.tycoon.xp-=xpForLevel(result.tycoon.level);result.tycoon.level++;}
    if(result.tycoon.level===MAX_EMPIRE_LEVEL) result.tycoon.xp=Math.min(result.tycoon.xp,xpForLevel(MAX_EMPIRE_LEVEL)-1);
    const rawSubscription=source.subscription&&typeof source.subscription==="object"?source.subscription:{};
    result.subscription={status:["free","trial","active"].includes(rawSubscription.status)?rawSubscription.status:"free",trialStartedAt:asInt(rawSubscription.trialStartedAt,0,0,Number.MAX_SAFE_INTEGER)||null,trialEndsAt:asInt(rawSubscription.trialEndsAt,0,0,Number.MAX_SAFE_INTEGER)||null,billingConsentAt:asInt(rawSubscription.billingConsentAt,0,0,Number.MAX_SAFE_INTEGER)||null,cancelledAt:asInt(rawSubscription.cancelledAt,0,0,Number.MAX_SAFE_INTEGER)||null,lastWeeklyBonusWeek:asText(rawSubscription.lastWeeklyBonusWeek,"",20)};
    const rawProfile=source.profile&&typeof source.profile==="object"?source.profile:{};
    result.profile={username:asText(rawProfile.username,"Rick",40),photo:safePhotoUrl(rawProfile.photo),verifiedContact:asText(rawProfile.verifiedContact,"",100),linkedAccounts:(Array.isArray(rawProfile.linkedAccounts)?rawProfile.linkedAccounts:seed.profile.linkedAccounts).slice(0,10).map((a,index)=>({id:asText(a?.id,"account-"+index,80),name:asText(a?.name,"Linked account",60),last4:asText(a?.last4,"0000",4).replace(/\D/g,"").slice(-4).padStart(4,"0")})),pendingChange:null};
    const pending=rawProfile.pendingChange; if(pending&&typeof pending==="object"&&asInt(pending.expiresAt,0,0,Number.MAX_SAFE_INTEGER)>now()) result.profile.pendingChange={username:asText(pending.username,result.profile.username,40),photo:safePhotoUrl(pending.photo),contact:asText(pending.contact,"",100),method:pending.method==="phone"?"phone":"email",expiresAt:asInt(pending.expiresAt,0,0,Number.MAX_SAFE_INTEGER)};
    return result;
  }
  function loadState(){try{return normaliseState(JSON.parse(storage.getItem(STORAGE_KEY)||"null"));}catch{return normaliseState(null);}}
  let state=loadState();
  function saveState(){try{storage.setItem(STORAGE_KEY,JSON.stringify(state)); if(typeof document!=="undefined") document.getElementById("syncStatus").textContent="Saved locally just now";}catch{if(typeof document!=="undefined") toast("Local storage is unavailable; this session cannot be saved.");}}
  function isPremium(){return state.subscription.status==="trial"||(state.subscription.status==="active"&&!state.subscription.cancelledAt);}
  function activeGoalCount(){return state.goals.filter(goal=>!goal.completed).length;}
  function remaining(goal){return Math.max(0,goal.target-goal.invested);}
  function addTransaction(label,kind,amount){state.transactions.unshift({id:makeId("tx"),label,kind,amount,createdAt:now()});state.transactions=state.transactions.slice(0,100);}
  function addPoints(amount,label,kind="Reward"){const safe=asInt(amount,0,0,MAX_POINTS);state.points=clamp(state.points+safe,0,MAX_POINTS);addTransaction(label,kind,safe);}
  function reconcile(){let changed=false, current=now(), sub=state.subscription;
    if(sub.status==="trial"&&sub.trialEndsAt&&current>=sub.trialEndsAt){sub.status=sub.cancelledAt?"free":"active";changed=true;}
    if(sub.cancelledAt&&sub.status==="active"){sub.status="free";changed=true;}
    if(isPremium()){const key=weekKey(current);if(sub.lastWeeklyBonusWeek!==key){sub.lastWeeklyBonusWeek=key;addPoints(100,"Premium weekly bonus");changed=true;}}
    if(changed) saveState(); return changed;
  }
  function awardXp(amount){const tycoon=state.tycoon;tycoon.xp=clamp(tycoon.xp+asInt(amount,0,0,MAX_POINTS),0,MAX_POINTS);let levels=0;while(tycoon.level<MAX_EMPIRE_LEVEL&&tycoon.xp>=xpForLevel(tycoon.level)){tycoon.xp-=xpForLevel(tycoon.level);tycoon.level++;levels++;}if(tycoon.level===MAX_EMPIRE_LEVEL)tycoon.xp=Math.min(tycoon.xp,xpForLevel(MAX_EMPIRE_LEVEL)-1);return levels;}
  function validateInvestment(goal,amount){const contribution=asInt(amount,-1,1,MAX_RUPEES);if(!goal)return {ok:false,message:"Choose a valid goal."};if(goal.completed||remaining(goal)===0)return {ok:false,message:"This goal is complete and cannot accept another investment."};if(contribution<1)return {ok:false,message:"Enter a whole-rupee amount of at least ₹1."};if(contribution>remaining(goal))return {ok:false,message:"Investment exceeds the remaining " + money(remaining(goal)) + "."};return {ok:true,amount:contribution};}
  function invest(goalId,amount,type){const goal=state.goals.find(item=>item.id===String(goalId));const verdict=validateInvestment(goal,amount);if(!verdict.ok)return verdict;goal.invested+=verdict.amount;goal.mode=type==="Lump sum"?"Lump sum":"Monthly SIP";if(goal.mode==="Monthly SIP")goal.monthly=verdict.amount;const earned=Math.max(5,Math.floor(verdict.amount/1000)*5);addPoints(earned,"Investment reward · "+goal.name);addTransaction("Investment · "+goal.name,goal.mode,-verdict.amount);let completion=0;if(goal.invested===goal.target&&!goal.completionAwarded){goal.completed=true;goal.completedAt=now();goal.completionAwarded=true;completion=250+(isPremium()?150:0);addPoints(completion,"Goal achieved · "+goal.name,"Completion bonus");awardXp(120);}return {ok:true,message:money(verdict.amount)+" invested in "+goal.name+". +"+earned+(completion?" +"+completion+" completion points.":" points.")};}
  function createGoal(name,target,description){if(!isPremium()&&activeGoalCount()>=FREE_ACTIVE_GOAL_LIMIT)return {ok:false,message:"Free membership allows three active goals. Start Premium for unlimited active goals."};const cleanName=asText(name,"",60), cleanTarget=asInt(target,0,100,MAX_RUPEES);if(!cleanName||!cleanTarget)return {ok:false,message:"Enter a name and a target from ₹100 to ₹1,00,00,00,000."};state.goals.push({id:makeId("goal"),name:cleanName,description:asText(description,"Financial goal",120),target:cleanTarget,invested:0,mode:"Monthly SIP",monthly:0,completed:false,completedAt:null,completionAwarded:false});return {ok:true,message:"Goal created: "+cleanName+"."};}
  function stageCost(def,stage){return stage>=5?0:def.costs[stage];}
  function buyStage(id){const def=BUILDINGS.find(item=>item.id===id);if(!def)return {ok:false,message:"Unknown building."};const stage=state.tycoon.buildings[def.id];if(state.tycoon.level<def.unlock)return {ok:false,message:def.name+" unlocks at Empire Level "+def.unlock+"."};if(stage>=5)return {ok:false,message:def.name+" is already at Stage 5."};const cost=stageCost(def,stage);if(state.points<cost)return {ok:false,message:"You need "+(cost-state.points)+" more reward points."};state.points-=cost;state.tycoon.buildings[def.id]=stage+1;addTransaction((stage?"Upgrade · ":"Built · ")+def.name,"Empire",-cost);const levels=awardXp(stage?85:140);return {ok:true,message:def.name+" is now Stage "+(stage+1)+". +"+(stage?85:140)+" XP"+(levels?" · Empire Level "+state.tycoon.level+"!":".")};}
  function randomInt(max){if(globalThis.crypto?.getRandomValues){const values=new Uint32Array(1);globalThis.crypto.getRandomValues(values);return values[0]%max;}return Math.floor(Math.random()*max);}
  function playRound(){if(state.points<25)return {ok:false,message:"You need 25 reward points to play."};state.points-=25;const roll=randomInt(100),coins=roll<12?150:roll<40?75:roll<72?30:0;state.gameCoins=clamp(state.gameCoins+coins,0,MAX_POINTS);state.tycoon.gamesPlayed++;state.tycoon.lastGameResult=coins?"You won "+coins+" game coins!":"No coins this round; your empire still keeps growing.";addTransaction("Reward round"+(coins?" · +"+coins+" coins":""),"Game",-25);if(coins)awardXp(20);return {ok:true,message:state.tycoon.lastGameResult};}
  function claimChallenge(id){const item=CHALLENGES.find(challenge=>challenge.id===id),today=new Date().toISOString().slice(0,10);if(!item)return {ok:false,message:"Unknown challenge."};if(state.tycoon.challenges[id]===today)return {ok:false,message:"That daily action is already claimed."};state.tycoon.challenges[id]=today;addPoints(item.points,item.label,"Daily action");const levels=awardXp(item.xp);return {ok:true,message:"+"+item.points+" points and +"+item.xp+" XP"+(levels?" · Level "+state.tycoon.level+"!":".")};}
  function calculateCashout(coins){const amount=asInt(coins,-1,MIN_CASHOUT_COINS,MAX_POINTS);if(amount<MIN_CASHOUT_COINS)return {ok:false,message:"Minimum cash-out is "+MIN_CASHOUT_COINS.toLocaleString("en-IN")+" coins."};if(amount%COINS_PER_RUPEE!==0)return {ok:false,message:"Use a multiple of "+COINS_PER_RUPEE+" coins."};if(amount>state.gameCoins)return {ok:false,message:"You only have "+state.gameCoins.toLocaleString("en-IN")+" game coins."};return {ok:true,coins:amount,rupees:amount/COINS_PER_RUPEE};}
  function requestCashout(coins,accountId){const verdict=calculateCashout(coins);if(!verdict.ok)return verdict;const bank=state.profile.linkedAccounts.find(item=>item.id===accountId);if(!bank)return {ok:false,message:"Select a linked bank account."};state.gameCoins-=verdict.coins;state.exchangeRequests.unshift({id:makeId("cashout"),coins:verdict.coins,rupees:verdict.rupees,accountId:bank.id,status:"Pending demo",createdAt:now()});addTransaction("Cash-out request · "+bank.name,"Exchange",-verdict.coins);return {ok:true,message:"Demo cash-out request for "+money(verdict.rupees)+" was created."};}
  function resetDemo(){state=normaliseState(clone(DEFAULT_STATE));return {ok:true,message:"Demo reset to the original sample values."};}
  function startTrial(consent){if(isPremium())return {ok:false,message:"Premium is already active."};if(!consent)return {ok:false,message:"Consent to monthly billing is required before a trial can start."};const started=now();state.subscription={status:"trial",trialStartedAt:started,trialEndsAt:started+TRIAL_DAYS*86400000,billingConsentAt:started,cancelledAt:null,lastWeeklyBonusWeek:""};reconcile();return {ok:true,message:"Your 7-day Premium trial is active. Cancel any time before billing."};}
  function cancelSubscription(){if(state.subscription.status==="free")return {ok:false,message:"There is no active Premium subscription to cancel."};const inTrial=state.subscription.status==="trial";state.subscription.cancelledAt=now();if(!inTrial)state.subscription.status="free";return {ok:true,message:inTrial?"Renewal cancelled. Trial benefits remain until the trial end.":"Premium renewal cancelled. Demo Premium benefits have ended."};}
  function toast(message){if(typeof document==="undefined")return;const node=document.getElementById("toast");node.textContent=message;node.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove("show"),3400);}
  function element(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;}
  function clear(node){if(node)node.replaceChildren();return node;}
  function addButton(parent,text,action,data={},className="btn small"){const button=element("button",className,text);button.type="button";button.dataset.action=action;Object.entries(data).forEach(([key,value])=>button.dataset[key]=value);parent.appendChild(button);return button;}
  function setText(id,text){const node=document.getElementById(id);if(node)node.textContent=text;}
  function renderAvatar(){const p=state.profile,initial=(p.username[0]||"G").toUpperCase(),photo=safePhotoUrl(p.photo);["avatarImage","bigAvatarImage"].forEach(id=>{const image=document.getElementById(id);if(image){image.hidden=!photo;if(photo)image.src=photo;else image.removeAttribute("src");}});setText("avatarInitial",initial);setText("bigAvatarInitial",initial);setText("topUsername",p.username);setText("profileName",p.username);setText("profileContact",p.verifiedContact?"Verified "+p.verifiedContact:"No verified contact");setText("profilePoints",state.points.toLocaleString("en-IN")+" reward points");}
  function goalCard(goal){const card=element("article","card goal-card"),head=element("div","row"),title=element("h3","",goal.name),badge=element("span","status"+(goal.completed?" gold":""),goal.completed?"Completed":"Active");head.append(title,badge);const desc=element("p","",goal.description),amount=element("div","amount",money(goal.target));const meta=element("div","goal-meta");meta.append(element("span","",money(goal.invested)+" invested"),element("b","",Math.round(goal.invested/goal.target*100)+"%"));const progress=element("div","progress"),fill=document.createElement("i");fill.style.width=(goal.invested/goal.target*100)+"%";progress.appendChild(fill);const sub=element("div","goal-meta");sub.append(element("span","",goal.mode+(goal.mode==="Monthly SIP"&&goal.monthly?" · "+money(goal.monthly)+"/month":"")),element("span","",goal.completed?"Goal reached":money(remaining(goal))+" remaining"));card.append(head,desc,amount,meta,progress,sub);if(!goal.completed)addButton(card,"Invest toward goal","select-invest",{goalId:goal.id},"btn small");return card;}
  function renderGoals(){const dashboard=clear(document.getElementById("dashboardGoals")),all=clear(document.getElementById("allGoals"));state.goals.forEach(goal=>{if(dashboard)dashboard.appendChild(goalCard(goal));if(all)all.appendChild(goalCard(goal));});if(!state.goals.length){const empty=element("div","empty","No goals yet.");dashboard?.appendChild(empty);all?.appendChild(empty.cloneNode(true));}const active=activeGoalCount(),completed=state.goals.length-active,total=state.goals.reduce((sum,goal)=>sum+goal.invested,0),target=state.goals.reduce((sum,goal)=>sum+goal.target,0);const stats=clear(document.getElementById("goalStats"));[["Total goals",state.goals.length],["Active goals",active],["Completed",completed],["Invested",money(total)]].forEach(([label,value])=>{const card=element("div","card stat-card");card.append(element("small","",label),element("b","",String(value)));stats?.appendChild(card);});setText("goalLimitStatus",isPremium()?"Premium · unlimited active goals":active+" / "+FREE_ACTIVE_GOAL_LIMIT+" free active goals");const select=document.getElementById("investmentGoal");if(select){const previous=select.value;clear(select);state.goals.filter(goal=>!goal.completed).forEach(goal=>{const option=document.createElement("option");option.value=goal.id;option.textContent=goal.name+" · "+money(remaining(goal))+" remaining";select.appendChild(option);});if([...select.options].some(option=>option.value===previous))select.value=previous;updateInvestmentLimit();}}
  function updateInvestmentLimit(){const select=document.getElementById("investmentGoal"),input=document.getElementById("investmentAmount"),hint=document.getElementById("investmentLimit");if(!select||!input||!hint)return;const goal=state.goals.find(item=>item.id===select.value);if(!goal){input.disabled=true;hint.textContent="All current goals are complete.";return;}const limit=remaining(goal);input.disabled=false;input.max=String(limit);hint.textContent="Remaining cap: "+money(limit)+". Larger amounts are rejected.";}
  function renderActivity(target,filter){const root=clear(document.getElementById(target));const rows=state.transactions.filter(filter||(()=>true)).slice(0,6);if(!rows.length){root?.appendChild(element("div","empty","No activity recorded yet."));return;}rows.forEach(row=>{const item=element("div","activity-row"),left=document.createElement("div");left.append(element("b","",row.label),element("small","",row.kind+" · "+dateTime(row.createdAt)));const quantity=Math.abs(row.amount).toLocaleString("en-IN"),shown=row.kind==="Investment"?money(Math.abs(row.amount)):quantity+(row.kind==="Exchange"?" coins":" pts");const amount=element("b",row.amount<0?"negative":"positive",(row.amount<0?"−":"+")+shown);item.append(left,amount);root?.appendChild(item);});}
  function renderDashboard(){setText("heroPoints",state.points.toLocaleString("en-IN"));setText("heroCoins",state.gameCoins.toLocaleString("en-IN"));const sub=state.subscription;setText("heroPremium",isPremium()?sub.status==="trial"?"Trial active":"Premium active":"Free plan");renderActivity("dashboardActivity");}
  function renderGame(){const t=state.tycoon,needed=xpForLevel(t.level),built=BUILDINGS.filter(def=>t.buildings[def.id]>0).length;setText("empireLevel",t.level);setText("empireXp",t.xp.toLocaleString("en-IN")+" / "+needed.toLocaleString("en-IN")+" XP");setText("empireBuildings",built+" / "+BUILDINGS.length+" built");setText("gameCoins",state.gameCoins.toLocaleString("en-IN"));setText("gameRoundResult",t.lastGameResult);const bar=document.getElementById("empireXpBar");if(bar)bar.style.width=(t.xp/needed*100)+"%";const next=BUILDINGS.find(def=>def.unlock>t.level);setText("empireUnlock",next?"Next unlock: "+next.name+" · Level "+next.unlock:"All properties unlocked");const container=clear(document.getElementById("buildings"));BUILDINGS.forEach(def=>{const stage=t.buildings[def.id],unlocked=t.level>=def.unlock,card=element("article","building"+(unlocked?"":" locked"));card.append(element("h3","",def.icon+" "+def.name),element("p","",def.description));const dots=element("div","stage-dots");for(let index=0;index<5;index++)dots.appendChild(element("i",index<stage?"on":""));card.appendChild(dots);const label=!unlocked?"Unlock at Level "+def.unlock:stage===5?"Stage 5 · Complete":"Stage "+stage+" → "+(stage+1)+" · "+stageCost(def,stage)+" pts";const button=addButton(card,label,"buy-building",{buildingId:def.id},"btn small");button.disabled=!unlocked||stage===5||state.points<stageCost(def,stage);container?.appendChild(card);});const today=new Date().toISOString().slice(0,10),challenges=clear(document.getElementById("challenges"));CHALLENGES.forEach(challenge=>{const line=element("div","challenge"),text=document.createElement("div");text.append(element("b","",challenge.label),element("small","",challenge.points+" points · "+challenge.xp+" XP"));line.appendChild(text);const claimed=t.challenges[challenge.id]===today,button=addButton(line,claimed?"Claimed":"Claim","claim-challenge",{challengeId:challenge.id},"btn small");button.disabled=claimed;challenges?.appendChild(line);});renderActivity("gameActivity",row=>row.kind==="Game"||row.kind==="Empire"||row.kind==="Daily action");}
  function subscriptionDescription(){const s=state.subscription;if(isPremium()&&s.status==="trial")return "Trial active until "+new Date(s.trialEndsAt).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"})+(s.cancelledAt?". Renewal is cancelled.":". ₹"+PREMIUM_MONTHLY_PRICE+"/month begins after the trial unless cancelled.");if(isPremium())return "Premium active. ₹"+PREMIUM_MONTHLY_PRICE+"/month subscription is simulated in this prototype.";return s.cancelledAt?"Subscription cancelled. Premium benefits have ended.":"Free plan: up to three active goals.";}
  function renderPremium(){setText("subscriptionState",subscriptionDescription());const button=document.getElementById("trialButton"),cancel=document.getElementById("cancelSubscriptionButton");if(button){button.disabled=isPremium();button.textContent=isPremium()?"Premium is active":"Start 7-day free trial";}if(cancel)cancel.disabled=!isPremium();}
  function renderAccount(){renderAvatar();setText("cashoutCoinBalance",state.gameCoins.toLocaleString("en-IN")+" coins available");const p=state.profile;const username=document.getElementById("profileUsername"),photo=document.getElementById("profilePhoto");if(username&&document.activeElement!==username)username.value=p.username;if(photo&&document.activeElement!==photo)photo.value=p.photo;const banks=clear(document.getElementById("bankAccounts")),bankSelect=clear(document.getElementById("exchangeBank"));p.linkedAccounts.forEach(account=>{const row=element("div","bank"),info=document.createElement("div");info.append(element("b","",account.name),element("small","","•••• "+account.last4+" · linked"));row.append(info,element("span","status","Verified"));banks?.appendChild(row);const option=document.createElement("option");option.value=account.id;option.textContent=account.name+" · •••• "+account.last4;bankSelect?.appendChild(option);});const pending=p.pendingChange,panel=clear(document.getElementById("verificationPanel"));if(pending){const note=element("div","notice info");note.append(element("b","","Verification requested."),document.createTextNode(" Confirm after completing the "+pending.method+" verification with "+pending.contact+". This demo UI does not impersonate an identity service."));panel?.appendChild(note);const confirm=addButton(panel,"Confirm verified change (demo)","confirm-profile",{},"btn small");confirm.style.marginTop="9px";}else panel?.appendChild(element("p","help","Changes expire after 15 minutes if verification is not completed."));updateExchangeQuote();const history=clear(document.getElementById("exchangeHistory"));if(!state.exchangeRequests.length){history?.appendChild(element("div","empty","No cash-out requests yet."));}else state.exchangeRequests.slice(0,8).forEach(request=>{const row=element("div","activity-row"),left=document.createElement("div");left.append(element("b","",money(request.rupees)+" · "+request.status),element("small","",request.coins.toLocaleString("en-IN")+" coins · "+dateTime(request.createdAt)));row.append(left,element("span","status gold","Demo only"));history?.appendChild(row);});}
  function updateExchangeQuote(){const input=document.getElementById("exchangeCoins"),quote=document.getElementById("exchangeQuote");if(!input||!quote)return;const coins=Number(input.value);quote.textContent=Number.isSafeInteger(coins)&&coins>0&&coins%COINS_PER_RUPEE===0?coins.toLocaleString("en-IN")+" coins = "+money(coins/COINS_PER_RUPEE):"Enter a multiple of "+COINS_PER_RUPEE+" coins to see the value.";}
  function render(){reconcile();if(typeof document==="undefined")return;renderDashboard();renderGoals();renderGame();renderPremium();renderAccount();renderAvatar();}
  function commit(result){if(result?.ok){saveState();render();toast(result.message);}else toast(result?.message||"That action could not be completed.");}
  function navigate(view){document.querySelectorAll(".page").forEach(page=>page.classList.toggle("active",page.id===view+"View"));document.querySelectorAll("[data-action='navigate']").forEach(button=>button.classList.toggle("active",button.dataset.view===view));if(typeof window!=="undefined")window.scrollTo({top:0,behavior:"smooth"});}
  function requestProfileVerification(form){const username=asText(form.username.value,"",40),method=form.method.value==="phone"?"phone":"email",contact=asText(form.contact.value,"",100),photo=safePhotoUrl(form.photo.value),password=form.password.value;const email=/^[^\s@]+@[^\s@]+\.[^\s@]+$/,phone=/^\+?[0-9]{10,15}$/;if(!username)return {ok:false,message:"Enter a username."};if(form.photo.value&& !photo)return {ok:false,message:"Profile photos must use a valid https URL."};if(!(method==="email"?email.test(contact):phone.test(contact)))return {ok:false,message:"Enter a valid "+method+" contact."};if(password&&password.length<12)return {ok:false,message:"Use at least 12 characters for a new password."};state.profile.pendingChange={username,photo,contact,method,expiresAt:now()+15*60*1000};return {ok:true,message:"Verification requested. Password data was intentionally not saved."};}
  function confirmProfileChange(){const pending=state.profile.pendingChange;if(!pending||pending.expiresAt<=now())return {ok:false,message:"No valid verification request is waiting."};state.profile.username=pending.username;state.profile.photo=pending.photo;state.profile.verifiedContact=pending.contact;state.profile.pendingChange=null;return {ok:true,message:"Profile change verified in this demo. Use a real identity provider in production."};}
  if(typeof document!=="undefined"){
    document.addEventListener("click",event=>{const button=event.target.closest("[data-action]");if(!button)return;const action=button.dataset.action;if(action==="navigate")navigate(button.dataset.view);else if(action==="reset-demo")commit(resetDemo());else if(action==="select-invest"){navigate("dashboard");const select=document.getElementById("investmentGoal");if(select){select.value=button.dataset.goalId;updateInvestmentLimit();document.getElementById("investmentAmount")?.focus();}}else if(action==="buy-building")commit(buyStage(button.dataset.buildingId));else if(action==="play-round")commit(playRound());else if(action==="claim-challenge")commit(claimChallenge(button.dataset.challengeId));else if(action==="cancel-subscription")commit(cancelSubscription());else if(action==="confirm-profile")commit(confirmProfileChange());});
    document.addEventListener("change",event=>{if(event.target.id==="investmentGoal")updateInvestmentLimit();if(event.target.id==="exchangeCoins")updateExchangeQuote();});document.addEventListener("input",event=>{if(event.target.id==="exchangeCoins")updateExchangeQuote();});
    document.addEventListener("submit",event=>{const form=event.target;if(!(form instanceof HTMLFormElement))return;event.preventDefault();if(form.id==="investForm")commit(invest(form.goal.value,form.amount.value,form.type.value));else if(form.id==="goalForm"){const result=createGoal(form.name.value,form.target.value,form.description.value);if(result.ok)form.reset();commit(result);}else if(form.id==="subscriptionForm")commit(startTrial(form.consent.checked));else if(form.id==="exchangeForm")commit(requestCashout(form.coins.value,form.bank.value));else if(form.id==="profileForm")commit(requestProfileVerification(form));});
    window.addEventListener("storage",event=>{if(event.key===STORAGE_KEY){state=loadState();render();toast("GoalGrow updated from another tab.");}});render();
  }
  /* Pure hooks make the critical invariants testable without a browser UI. */
  globalThis.GoalGrowTestHooks={normaliseState,validateInvestment,xpForLevel,calculateCashout:coins=>calculateCashout(coins),getState:()=>clone(state),setState:value=>{state=normaliseState(value);},resetDemo:()=>resetDemo(),invest:(id,amount,type)=>invest(id,amount,type),createGoal:(name,target,description)=>createGoal(name,target,description),awardXp:(amount)=>awardXp(amount),buyStage:(id)=>buyStage(id),startTrial:(consent)=>startTrial(consent),cancelSubscription:()=>cancelSubscription(),COINS_PER_RUPEE,MIN_CASHOUT_COINS,MAX_EMPIRE_LEVEL};
